version: "3.7"
services:
    my-engine:
        privileged: true
        devices:
        - "/dev/fuse:/dev/fuse"
        container_name: your-web
        build: ./app/
        image: your-image:1.0
        ports:
            - 80:80
            - 443:443
            - 7080:7080
        environment:
            DOMAIN: localhost
        networks: 
            - backend
networks:
    backend:
        name: your_network