version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: "monio-storage"
    ports:
      - "9000:9000"
      - "9022:9022"
    volumes:
      - minio-storage:/data
    environment:
      - "MINIO_ROOT_USER=minio_access_key"
      - "MINIO_ROOT_PASSWORD=minio_secret_key"
      - "MINIO_SERVER_URL=https://assets.yourdomain.com"
      - "MINIO_BROWSER_REDIRECT_URL=https://minio.yourdomain.com"
      - "MINIO_HTTP_TRACE=/var/log/minio.log"
    command: server --console-address :9022 /data

volumes:
  minio-storage:
    external: true