version: '3.7'
services:
  dws:
    privileged: true
    devices:
    - "/dev/fuse:/dev/fuse"
    build: ./app
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
