version: '3.8'
services:
  pgsql-db:
    build: .
    container_name: pgsql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yoursecret
    ports:
      - '5432:5432'
    volumes: 
      - db-vol:/var/lib/postgresql/data
volumes:
  db-vol:
    driver: local